#AllCops:
#  Exclude:
#    - lib/kata.rb
Style/FrozenStringLiteralComment:
  Enabled: false
Lint/UnifiedInteger:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/LineLength:
  Exclude:
    - 'spec/**/*'
Eval:
  Exclude:
    - 'spec/**/*'
